# Profiles para conexão do dbt com o Databricks
# Docs: https://docs.getdbt.com/docs/core/connect-data-platform/databricks-setup

# O nome 'cea_aw' combina com o profile definido no dbt_project.yml
cea_aw:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: dev_cea_aw
      host: dbc-56352174-c77f.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b83ff5bf59f6214a
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

    prod:
      type: databricks
      catalog: workspace
      schema: cea_aw
      host: dbc-56352174-c77f.cloud.databricks.com
      http_path: /sql/1.0/warehouses/b83ff5bf59f6214a
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
